mail:
  build: mail
  env_file:
    - .env
  links:
    - mysql
    - opendkim
    - spamassassin
  volumes:
    - "./data/certs:/etc/certs"
  volumes_from:
    - storagebackup
  ports:
    - "${PORT_MAIL_SMTP}:25"
    - "${PORT_MAIL_SECURE_SMTP}:587"
    - "${PORT_MAIL_IMAP}:993"
  restart: always

opendkim:
  build: opendkim
  env_file:
    - .env
  expose:
    - "8891"
  volumes:
    - "./data/certs:/etc/certs"
  restart: always

spamassassin:
  build: spamassassin
  expose:
    - "783"
  volumes_from:
    - storagebackup
  restart: always

mysql:
  build: mysql
  environment:
    - "MYSQL_ROOT_PASSWORD=password"
  env_file:
    - .env
  volumes:
    - "./data/backup:/backup"
  expose:
    - "3306"
  restart: always

# Storage container for vmail that also creates daily backups
storagebackup:
  build: storagebackup
  env_file:
    - .env
  links:
    - mysql
  volumes:
    - "/var/vmail"
    - "./data/backup:/backup"
    - "/var/spamassassin"
  restart: always

# If you only want the mail server and no webmail/admin simply remove webserver and memcache
webserver:
  build: webserver
  env_file:
    - .env
  ports:
    - "${PORT_WEB_HTTP}:80"
  volumes:
    - "./data/certs:/etc/certs"
  volumes_from:
    - storagebackup
  links:
    - mysql
    - memcache
    - mail
  restart: always

memcache:
  build: memcache
  expose:
    - "11211"
  restart: always
